This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./monografia.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file monografia.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (21 comparisons).
Generating output file monografia.acr....done (19 lines written, 0 warnings).
Output written in monografia.acr.
Transcript written in monografia.alg.
