\chapter*{Agradecimentos} Primeiramente a Deus, sem
quem nada é possível e por @@latex:\mbox{\textbf{todas}}@@ as pessoas colocadas em meu caminho, que
me fizeram crescer e ser o indivíduo que hoje sou.

* Meus Pais :ignore:
  Aos meus pais, Rosemeri e Rogério. Por todo amor, carinho, atenção e
  apoio dados, pela primeira educação, essencial para toda minha
  trajetória, educação não só acadêmica, mas também moral. Obrigado, por tudo ! Amo muito vocês.

* Professores (Colégio Aplicação de Vista Alegre, Adlai Stevenson, Colégio Pedro II, CEFET ) :ignore:
  A todas minhas professoras e professores por 
   mostrarem o quão importante e bonita é a profissão e por terem sempre
   instigado a sede pelo aprendizado. Agradeço àqueles que contribuíram para
   minha base acadêmica e profissional.

* Colegas dos colégios :ignore:
As amizades que fiz, as que se foram de minha convivência e
   as que permaneceram, agradeço aqueles que conheci na UFRJ, mais especificamente a nossa turma T17,
   pois se chegamos até onde chegamos foi porque estivemos juntos, fortes, ombro
   no ombro, tentando não deixar o outro cair, mas quando alguém caía
   sempre uma mão amiga se estendia para ajudar a levantar e recomeçar. 

Ao Paulo Yamasaki, pelo convívio no LABECA, e pelas
   trocas de ideias em assuntos gerais que por fim, intencionalmente ou não, se
   tornariam orientação em diversos projetos que fiz na faculdade, e até mesmo
   orientação acadêmica e profissional. 

Aos melhores companheiros de grupo, Gabriel Pelielo e Rodrigo Moysés, um
verdadeiro ``Power Trio''. Também a Philipe Moura e Felipe Matheus, que me
incentivaram a sair da minha zona de conforto e me fizeram compreender de fato o sentido do quão
``perigoso'' é sair pela porta de casa, pois quando saímos da nossa zona de
conforto, coisas mágicas podem acontecer e pessoas mágicas podem aparecer em
nossas vidas.

* Evelise :ignore:
À Evelise, a pessoa mágica que apareceu em minha vida, que me ajudou
fisicamente e psicologicamente nos momentos que mais precisei. Obrigado por escolher compartilhar parte de sua
vida comigo e por toda a força dada para o término desse ciclo. Eu te amo!  

* Orientador :ignore:
Por fim às pessoas que me ajudaram mais diretamente neste projeto, Ryan
Pitanga e ao meu orientador Marcos Moreira 

#+BEGIN_EXPORT latex
%%% Local Variables: mode: latex TeX-master: "../monografia.tex" End:
#+END_EXPORT

