#!/bin/bash

# Places
# echo "#+ATTR_LATEX: :caption \caption{Complete Places.} :environment longtable :align m{5cm}m{5cm}"
echo "#+ATTR_LATEX: :caption \caption{Complete Places.} :environment longtable :align m{5cm}m{5cm}"
echo "| Places | Meaning |"
echo "|----+---------|"
echo -e "$(sed -n "5,33p" ../1-initialization/initial.org)\n" \
     "$(sed -n "5,27p" ../2-metalv/metalv.org)\n" \
"$(sed -n "5,27p" ../3-plastic^/plastic.org)\n" \
"$(sed -n "5,17p" ../4-armBeltToPress/armBeltToPress.org)\n" \
"$(sed -n "5,13p" ../5-press/press.org)\n" \
"$(sed -n "5,16p" ../6-armPressToStorage/armPressToStorage.org)\n" \
 "$(sed -n "5,14p" ../7-storageY/storageY.org)\n" \
 "$(sed -n "5,16p" ../8-storageX/storageX.org)\n" \
 "$(sed -n "5,14p" ../9-storePiece/storePiece.org)" \
    | sed -E "s|\ +|\ |g;" | sed "s(\ |(|(g;s(|\ (|(g" \
    | awk -F'|' '{a[$3]=a[$3]", c"$2;}END{for (x in a) print "|" substr(a[x],2)"|"  x "|";}' | sort -V

echo ""
echo "#+ATTR_LATEX: :caption \caption{Complete Transitions.} :environment longtable :align m{5cm}m{5cm}"
echo "| Transitions | Meaning |"
echo "|----+---------|"
#Transitions
echo -e "$(sed -n "37,56p" ../1-initialization/initial.org)\n" \
     "$(sed -n "32,57p" ../2-metalv/metalv.org)\n" \
     "$(sed -n "32,57p" ../3-plastic^/plastic.org)\n" \
     "$(sed -n "22,35p" ../4-armBeltToPress/armBeltToPress.org)\n" \
     "$(sed -n "19,26p" ../5-press/press.org)\n" \
     "$(sed -n "21,31p" ../6-armPressToStorage/armPressToStorage.org)\n" \
     "$(sed -n "20,35p" ../7-storageY/storageY.org)\n" \
     "$(sed -n "21,44p" ../8-storageX/storageX.org)\n" \
     "$(sed -n "19,28p" ../9-storePiece/storePiece.org)" \
    | sed -E "s|\ +|\ |g;" | sed "s(\ |(|(g;s(|\ (|(g" \
    | awk -F'|' '{a[$3]=a[$3]", c"$2;}END{for (x in a) print "|" substr(a[x],2)"|"  x "|";}' | sort -V

