#!/bin/bash
function getPetriNet {
    cat $1 | sed -n -e '/^# PetriNetBegin$/,/^# PetriNetEnd$/!d;p' | sed '5,$!d' | sed '$d' | sed "s;^\ *;;" | sed -E "s/e([tp])(t|)([0-9]+)(|m[0-9]+)/\1\2\3\4/" | sed -E "s/^#[^#](.*)/\1/" | sed /^#/d
}


echo 'digraph A {
splines = ortho
rankdir=LR;
ratio=fill
graph [pad="0.5", nodesep="0.25", ranksep="0.2", nodesep="0.2"];
margin=0;
size="1.41,1!";
'
echo -e "$(getPetriNet ../1-initialization/initial.dot)\n" \
     "$(getPetriNet ../2-metalv/metalv.dot)\n" \
     "$(getPetriNet ../3-plastic^/plastic.dot)\n" \
     "$(getPetriNet ../4-armBeltToPress/armBeltToPress.dot)\n" \
     "$(getPetriNet ../5-press/press.dot)\n" \
     "$(getPetriNet ../6-armPressToStorage/armPressToStorage.dot)\n" \
     "$(getPetriNet ../7-storageY/storageY.dot)\n" \
     "$(getPetriNet ../8-storageX/storageX.dot)\n" \
     "$(getPetriNet ../9-storePiece/storePiece.dot)" \
    | sed -E "s|[[:space:]]+| |g;s|^\ *||;s|[[:space:]]*$||" | awk '/(^label|^}|^style)/ { print; next; }; !seen[$0]++' | sed -E "s;([tp])(t|)([0-9]+)(|m[0-9]+);c\1\2\3\4;g"

echo "}"
