#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""

@author: Accacio
"""

# nuitka --recurse-on --python-version=3.6 daoct;

import sys
import getopt
import utils as ut
import daoct as at

# config variables
version=0.0
inputFiles=[]
outputFile=""
verbose=False
graphviz=False
ffunction=False
fromStdin=False
debug=False
paramk=2
fullReport=False

def usage():
    print("Usage: daoct [OPTION] -i FILE ...")
    print("       daoct [OPTION] -s")
    print("")
    print("  -h, --help             give this help list")
    print("      --debug            emit debuggin messages")
    print("      --version          print program version")
    print("  -i, --input            chooses input file")
    print("  -s, --stdin            chooses stdin as input")
    # print("  -o, --output           chooses output file")
    print("  -k                     chooses variable k value")
    print("  -g, --graphviz         output automaton drawing in dot language")
    print("  -f, --ffunction        output automaton in f function")
    print("  -r, --report           output automaton Full Report")
    print("")
    print("Report bugs to raccacio@poli.ufrj.br")
    return

try:
    opts, args = getopt.gnu_getopt(sys.argv[1:],"k:srhgfi:o:",["input=","output=","verbose","graphviz","ffunction","debug","version","paramk=","report"])
except getopt.GetoptError:
    usage()
    sys.exit(-1)

if opts==[] or opts==[('--debug','')]or opts in [('--verbose','')]:
    usage()
    sys.exit(-1)


files=[]
for opt, arg in opts:
    if opt in ("-h","--help"):
        usage()
        sys.exit()
    if opt in ("--version"):
        print("VERSION:",version)
        sys.exit()
    if opt in ("--verbose"):
        verbose=True
    if opt in ("-g","--graphviz"):
        graphviz=True
    if opt in ("-f","--ffunction"):
        ffunction=True
    if opt in ("-r","--report"):
        fullReport=True
    if opt in ("-k"):
        paramk=int(arg)
    if opt in ("--debug"):
        debug=True
    if opt in ("-i", "--input"):
        inputFiles.append(arg)
    if opt in ("-s", "--stdin"):
        fromStdin=True
    if opt in ("-o", "--output"):
        outputFile=arg

myutil = ut.MyUtil(verbose,debug)
if inputFiles==[] and fromStdin==True:
    try:
        files.append(sys.stdin.readlines())
    except KeyboardInterrupt:
        sys.stdout.flush()
        sys.exit(-1)
elif inputFiles!=[]:
    try:
        for inputFile in inputFiles:
            files.append(open(inputFile,newline=''))
        # filedata=file.read()
    except FileNotFoundError:
        print("File not Found, please insert a valid file name")
        sys.exit(-1)
else:
    usage()
    sys.exit(-1)



myutil.printd("VERSION          :",version)
myutil.printd("ARGUMENTS        :",sys.argv[:])
myutil.printd("OPTS             :",opts)
myutil.printd("ARGS             :",args)
myutil.printd("VERBOSE          :",verbose)
myutil.printd("GRAPHVIZ         :",graphviz)
myutil.printd("INPUTFILES       :",inputFiles)
myutil.printd("OUTPUT FILE NAME :",outputFile)
myutil.printd("PARAMETER k      :",paramk)

# myTR = ut.TableReader(files,verbose,debug)
# records = myTR.getRecordFromFile()
# myPM = ut.PathManager(records,verbose,debug)
# paths = myPM.getPaths()
# modifiedPaths, modifiedSigmas = myPM.getModifiedPaths(paramk)

daoct=at.DAOCT(files,paramk,verbose,debug)



if fullReport:
    # print("==== Paths  ====")
    # daoct.printPath(daoct.paths)
    # print("==== Modified Paths k=",daoct.k, " ====",sep='')
    # daoct.printModifiedPaths(daoct.pK)
    # print("==== Automaton f ====")
    # daoct.printAutomaton();
    # print("")
    # print("==== Graphviz  ====")
    # daoct.graphvizAutomaton();
    # print("")
    # print("==== Exceeding Language  ====")
    # daoct.graphvizAutomaton();
    # print(daoct.LangLessNNDAAO(daoct.x0,10))
    # print(daoct.getAutoTracesDAOCT(daoct.x0,9,daoct.R))
    print(daoct.getAutoTracesDAOCTLessN(daoct.x0,2,daoct.R,0))
    # print(daoct.LangLessNDAOCT(daoct.x0,7))

else:
    if graphviz and not debug:
        daoct.graphvizAutomaton();
    if ffunction and not debug:
        daoct.printAutomaton();


# print("original")
# myPM.printPathd(paths)
# print("modified")
# myPM.printModifiedPathsd(modifiedPaths)

